JointDataArray[] vel_traj
JointDataArray initial_pos
---
bool success
JointDataArray[] o_t_ee
JointDataArray[] o_t_ee_d
JointDataArray[] f_t_ee
JointDataArray[] f_t_ne
JointDataArray[] ne_t_ee
JointDataArray[] ee_t_k
JointDataArray m_ee
JointDataArray[] i_ee
JointDataArray[] f_x_cee
JointDataArray m_load
JointDataArray[] i_load
JointDataArray[] f_x_cload
JointDataArray m_total
JointDataArray[] i_total
JointDataArray[] f_x_ctotal
JointDataArray[] elbow
JointDataArray[] elbow_d
JointDataArray[] elbow_c
JointDataArray[] delbow_c
JointDataArray[] ddelbow_c
JointDataArray[] tau_j
JointDataArray[] tau_j_d
JointDataArray[] dtau_j
JointDataArray[] q
JointDataArray[] q_d
JointDataArray[] dq
JointDataArray[] dq_d
JointDataArray[] ddq_d
JointDataArray[] joint_contact
JointDataArray[] cartesian_contact
JointDataArray[] joint_collision
JointDataArray[] cartesian_collision
JointDataArray[] tau_ext_hat_filtered
JointDataArray[] o_f_ext_hat_k
JointDataArray[] k_f_ext_hat_k
JointDataArray[] o_dp_ee_d
JointDataArray[] o_t_ee_c
JointDataArray[] o_dp_ee_c
JointDataArray[] o_ddp_ee_c
JointDataArray[] theta
JointDataArray[] dtheta
